#!/bin/python3


import math
import os
import random
import re
import sys
import string

# Complete the pangrams function below.
def pangrams(s):
    for i in string.whitespace + string.punctuation:
        if i in s:
            s = s.replace(i, '')
        if len(set(s)) == 26:
            return "pangram"
        else:
            return "not pangram"
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = pangrams(s)

    fptr.write(result + '\n')

    fptr.close()
